
services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 3333:8080
